# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 19:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Project Name')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('state', models.CharField(max_length=40, verbose_name='State/Province')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
                ('project_type', models.CharField(choices=[('1', 'City'), ('2', 'Campus'), ('3', 'Supply')], max_length=1, verbose_name='Project Type')),
                ('project_subtype', models.CharField(choices=[('1', 'Municipal Utility'), ('2', 'Special District'), ('3', 'City Wide'), ('4', 'Investor Owned'), ('5', 'University campus'), ('6', 'Industrial Park'), ('7', 'Military Base'), ('8', 'Large Building'), ('9', 'CHP Power Plant'), ('10', 'Industrial Facility'), ('11', 'Third Party Supplier'), ('12', 'Other')], max_length=2, verbose_name='Project SubType')),
                ('org_name', models.CharField(max_length=80, verbose_name='Organization Name')),
                ('org_address', models.TextField(verbose_name='organisation Address')),
                ('poc_name', models.CharField(max_length=80, verbose_name='Point Of Contact Name')),
                ('poc_contact', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$'), django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(15)], verbose_name='Contact Number')),
                ('poc_email', models.EmailField(max_length=80, verbose_name='Point of Contact Email')),
                ('poc_designation', models.CharField(max_length=80, verbose_name='Point of Contact Designation')),
                ('status', models.CharField(choices=[('1', 'Basic'), ('2', 'Screening')], max_length=1, verbose_name='Project Status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Project Unique ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_create_by', to=settings.AUTH_USER_MODEL)),
                ('destroyed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_destroyed_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
