# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspecificinfo',
            name='hydro_elec',
            field=models.IntegerField(blank=True, default=0, verbose_name='Hydro Electricity Generation'),
        ),
    ]
