# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_subtype',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project',
            name='zipcode',
            field=models.CharField(default=123456, max_length=20, verbose_name='Zipcode'),
            preserve_default=False,
        ),
    ]
