# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyquestion',
            name='interruption_range',
            field=models.CharField(blank=True, choices=[('1', 'O to < 15 mins'), ('2', '>15 mins to 60 mins'), ('3', 'More than 60 mins')], max_length=1, null=True, verbose_name='Interruption Frequency Range'),
        ),
    ]
