# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectspecificinfo_hydro_elec'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspecificinfo',
            name='hydro_elec_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hydro Electricity Generation'),
        ),
    ]
