# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_strategyquestion_interruption_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditsKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='keyword')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Keyword Description')),
            ],
            options={
                'verbose_name': 'CreditsKeyword',
                'verbose_name_plural': 'CreditsKeywords',
            },
        ),
    ]
