# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectspecificinfo_hydro_elec_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspecificinfo',
            name='annual_fuel_cost',
            field=models.IntegerField(default=0, verbose_name='Annual Fuel Cost'),
        ),
    ]
