# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectspecificinfo_annual_fuel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspecificinfo',
            name='all_customer_class',
            field=models.BooleanField(default=False, verbose_name='All Customer Classes'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='all_generator_type',
            field=models.BooleanField(default=False, verbose_name='All Generator Type'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='current_customer_meter_perc',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Customer percentage Installed Advance Meter'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='customer_meter_perc',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Customer percentage Installed Advance Meter'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='customer_served_meter_perc',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Customer Served by Meter in last 4yrs'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='meter_aggregation',
            field=models.BooleanField(default=False, verbose_name='Meter Aggregation'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='third_party_ownership',
            field=models.BooleanField(default=False, verbose_name='Thirdparty Ownership Generation'),
        ),
    ]
