# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_creditskeyword_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategyquestion',
            name='interruption_range',
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_answered_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
