# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160809_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='org_address',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('city', 'City'), ('campus', 'Campus'), ('supply', 'Supply')], max_length=10, null=True, verbose_name='Project Type'),
        ),
    ]
