# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160821_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspecificinfo',
            name='bulk_sei',
            field=models.FloatField(blank=True, null=True, verbose_name='Bulk SEI value'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='customer_elec_load_supplied',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage of Customer Electricity Load Supplied'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='ees_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Electricity Efficiency Savings'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='lre_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='LRE Strategy Score'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='net_metering_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Net Metering Score'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='oe_credit_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='OE Credit Score'),
        ),
        migrations.AlterField(
            model_name='electricityplant',
            name='fuel_type',
            field=models.CharField(choices=[('coal', 'Coal'), ('nuclear', 'Nuclear'), ('cas', 'Gas'), ('Petroleum', 'Petroleum'), ('simple gas', 'Simple Gas'), ('wind', 'Wind'), ('hydro', 'Hydro'), ('other', 'Other')], default='other', max_length=20, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('City', 'City'), ('Campus', 'Campus'), ('Supply', 'Supply')], max_length=10, null=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='projectplant',
            name='fuel_type',
            field=models.CharField(choices=[('coal', 'Coal'), ('nuclear', 'Nuclear'), ('gas', 'Gas'), ('petroleum', 'Petroleum'), ('simple-gas', 'Simple Gas'), ('wind', 'Wind'), ('other', 'Other')], default='other', max_length=20, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'Dollar'), ('INR', 'Rupee')], max_length=20, null=True, verbose_name='Default Currency'),
        ),
    ]
