# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160810_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectquestion',
            name='output',
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='bool_output',
            field=models.NullBooleanField(verbose_name='Question output for boolean fields'),
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='data_output',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Question output for data fields'),
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='frequency_output',
            field=models.CharField(blank=True, choices=[('1', '0 to < 15 mins'), ('2', '> 15 mins to 60 mins'), ('3', 'More than 60 mins')], max_length=1, null=True, verbose_name='Question output for choice output'),
        ),
    ]
