# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160825_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspecificinfo',
            name='sei_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Project Score'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='annual_fuel_cost',
            field=models.IntegerField(default=0, verbose_name='Avrage Annual Fuel Cost'),
        ),
    ]
