# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-13 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160811_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Default Currency'),
        ),
        migrations.AddField(
            model_name='project',
            name='electricity_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Electricity Default Unit'),
        ),
        migrations.AddField(
            model_name='project',
            name='thermal_unit',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Thermal/Heat Energy Unit'),
        ),
    ]
