# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160825_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='sei_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='SEI Score'),
        ),
    ]
