# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-14 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160813_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspecificinfo',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Default Currency'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='electricity_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Electricity Default Unit'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='thermal_unit',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Thermal/Heat Energy Unit'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='annual_customer_load',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Annual Customer Load'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='annual_purchased_elec',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Annual Purchased Electricity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='biomass_elec',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Biomass Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='biomass_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Biomass Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='chp_elec',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Local CHP natual gas Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='chp_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Local CHP natual gas Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='customer_hr_peak_demand',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Customer Annual Hourly Peak Demand'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='geothermal_elec',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Geothermal Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='geothermal_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Geothermal Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='high_efficiency_gas_elec',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Local High Efficiency Electricity generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='high_efficiency_gas_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Local High Efficiency Electricity generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='local_other_gas_elec',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Local other Gas Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='local_other_gas_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Local other Gas Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='other_local_elec',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Other Renewable Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='other_local_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Other Renewable Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='purchased_hr_peak_demand',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Purchased annual hourly peak demand'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='tnd_losses',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='T&D Losses'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='tot_local_elec_generation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Local Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='tot_local_generation_capacity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Local Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='turbine_elec',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Local Turbine Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='turbine_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Local Turbine Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='wind_solar_pv_elec',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Wind Solar PV Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='wind_solar_pv_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Wind Solar PV Electricity Generation Capacity'),
        ),
    ]
