# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160814_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsachieved',
            name='intent',
            field=models.TextField(verbose_name='Credit Intent'),
        ),
        migrations.AlterField(
            model_name='strategyquestion',
            name='code',
            field=models.CharField(choices=[('RRS11', 'RRS-1.1'), ('RRS12', 'RRS-1.2'), ('RRS13', 'RRS-1.3'), ('RRC14', 'RRC-1.4'), ('RRC15', 'RRC-1.5'), ('RRC16', 'RRC-1.6'), ('RRS17', 'RRS-1.7'), ('RRC18', 'RRC-1.8'), ('EES31', 'EES-3.1'), ('EES32', 'EES-3.2'), ('EES33', 'EES-3.3'), ('EES34', 'EES-3.4'), ('EEC35', 'EEC-3.5'), ('EES121', 'EES-12.1'), ('EEC122', 'EEC-12.2'), ('OES61', 'OES-6.1'), ('OEC62', 'OEC-6.2'), ('CCC11', 'CCC-1.1'), ('CCC12', 'CCC-1.2'), ('CCC13', 'CCC-1.3'), ('CCC14', 'CCC-1.4'), ('CCC15', 'CCC-1.5'), ('CCC16', 'CCC-1.6'), ('CCC17', 'CCC-1.7'), ('CCS11', 'CCS-1.1'), ('CCS12', 'CCS-1.2'), ('CCS13', 'CCS-1.3'), ('CCS14', 'CCS-1.4'), ('CCS15', 'CCS-1.5'), ('CCS16', 'CCS-1.6'), ('CCS17', 'CCS-1.7'), ('CCS18', 'CCS-1.8')], max_length=10, verbose_name='Question Code'),
        ),
    ]
