# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160825_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('CITY', 'City'), ('CAMPUS', 'Campus'), ('SUPPLY', 'Supply')], max_length=10, null=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='project_score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Project Score'),
        ),
    ]
