# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160826_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.CharField(max_length=5, verbose_name='Country'),
        ),
    ]
