# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160814_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Project Region'),
        ),
    ]
