# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspecificinfo',
            name='customer_served',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Customer Served with Advance Meter'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='frequency_range',
            field=models.CharField(blank=True, choices=[('FRQ1', 'O to < 15 mins'), ('FRQ2', '>15 mins to 60 mins'), ('FRQ3', 'More than 60 mins')], max_length=5, null=True, verbose_name='Interruption Frequency Range'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='annual_customer_load',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Annual Customer Load'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='annual_purchased_elec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Annual Purchased Electricity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='biomass_elec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Biomass Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='biomass_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Biomass Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='chp_elec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Local CHP natual gas Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='chp_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Local CHP natual gas Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='customer_hr_peak_demand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Customer Annual Hourly Peak Demand'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='geothermal_elec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Geothermal Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='geothermal_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Geothermal Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='high_efficiency_gas_elec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Local High Efficiency Electricity generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='high_efficiency_gas_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Local High Efficiency Electricity generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='local_other_gas_elec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Local other Gas Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='local_other_gas_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Local other Gas Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='other_local_elec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Other Renewable Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='other_local_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Other Renewable Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='purchased_hr_peak_demand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchased annual hourly peak demand'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='tnd_losses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='T&D Losses'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='tot_local_elec_generation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Local Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='tot_local_generation_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Local Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='turbine_elec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Local Turbine Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='turbine_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Local Turbine Electricity Generation Capacity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='wind_solar_pv_elec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Wind Solar PV Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='wind_solar_pv_elec_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Wind Solar PV Electricity Generation Capacity'),
        ),
    ]
