# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0014_auto_20160815_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=projects.models.question_file_upload, verbose_name='Question File for Project')),
                ('status', models.CharField(default='completed', max_length=20, verbose_name='Strategy Status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_question', to='projects.Project')),
            ],
            options={
                'verbose_name': 'ProjectStrategy',
                'verbose_name_plural': 'ProjectStrategys',
            },
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='strategy',
            name='unique_id',
            field=models.CharField(choices=[('amr1a', 'Advance Metering 1A'), ('amr1b', 'Advance Metering 1B'), ('seiee', 'Source Energy Intensity EE'), ('lrgee', 'Local Renewable Generation EE'), ('eeeoe', 'Electricity Energy Efficiency OE'), ('amicc', 'Advance Metering Infrastructure CC'), ('ntmcc', 'Net Metering CC')], default=1, max_length=5, verbose_name='Strategy Unique ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectQuestion',
        ),
        migrations.AddField(
            model_name='projectstrategy',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_strategy', to='projects.Strategy'),
        ),
        migrations.AddField(
            model_name='projectstrategy',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answered_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
