# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20160816_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plant Name')),
                ('fuel_type', models.CharField(choices=[('coal', 'Coal'), ('nuclear', 'Nuclear'), ('cas', 'Gas'), ('other mean', 'Other')], default='other mean', max_length=20, verbose_name='Fuel Type')),
                ('sei_value', models.CharField(default=0, max_length=10, verbose_name='SEI Value')),
                ('utility', models.CharField(choices=[('NTPC', 'NTPC'), ('NHPC', 'NHPC'), ('NPCIL', 'NPCIL'), ('IPGPCL', 'IPGPCL'), ('SEI', 'SEI Solar Energy Pvt. Ltd.')], max_length=10, verbose_name='Plant Utility')),
                ('type', models.CharField(choices=[('TRL', 'Thermal'), ('HDR', 'Hydro'), ('PV', 'PV')], max_length=10, verbose_name='Plant Type')),
                ('state', models.CharField(max_length=30, verbose_name='Plant State')),
                ('country', models.CharField(max_length=30, verbose_name='Plant Country')),
                ('electricity_delivered', models.CharField(default=0, max_length=10, verbose_name='Electricity Delivered to Project')),
                ('generation_type', models.CharField(choices=[('local', 'Local'), ('bulk', 'Bulk')], max_length=10, verbose_name='Type of Generation')),
                ('thermal_energy', models.CharField(max_length=15, verbose_name='Recovered Thermal Energy')),
                ('delete', models.BooleanField(default=True, verbose_name='Delete')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_plant', to='projects.Project')),
            ],
            options={
                'verbose_name': 'ElectricityPlant',
                'verbose_name_plural': 'ElectricityPlants',
            },
        ),
        migrations.CreateModel(
            name='ProjectPlantUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.IntegerField(verbose_name='Plant Unit No.')),
                ('capacity', models.CharField(max_length=10, verbose_name='Plant Unit capacity')),
                ('commissioning', models.DateTimeField(blank=True, null=True, verbose_name='Plant Commissioning Date')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_plant_unit', to='projects.ProjectPlant')),
            ],
            options={
                'verbose_name': 'ElectricityPlantUnit',
                'verbose_name_plural': 'ElectricityPlantUnits',
            },
        ),
        migrations.RemoveField(
            model_name='projectplantmapping',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='projectplantmapping',
            name='plant_unit',
        ),
        migrations.RemoveField(
            model_name='projectplantmapping',
            name='project',
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='bulk_coal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchased Bulk Coal Electricity'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='bulk_high_eff_gas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchased Bulk High Efficiency Electricity'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='bulk_hydro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchased Bulk Hydro Electricity'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='bulk_nuclear',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchased Bulk Nuclear Electricity'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='bulk_petroleum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchased Bulk Petroleum Electricity'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='bulk_simple_gas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchased Bulk Simple Gas Electricity'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='bulk_solar_pv_wind',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchased Bulk Solar and Wind Electricity'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('mga', 'Micro Grid 8760 Analysis'), ('scr', 'Screening'), ('ppp', 'PEER Participation Package')], max_length=3, null=True, verbose_name='Payment Option'),
        ),
        migrations.AddField(
            model_name='projectspecificinfo',
            name='sei',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Project SEI value'),
        ),
        migrations.DeleteModel(
            name='ProjectPlantMapping',
        ),
    ]
