# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20160816_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectplant',
            options={'verbose_name': 'ProjectPlant', 'verbose_name_plural': 'ProjectPlants'},
        ),
        migrations.AlterModelOptions(
            name='projectplantunit',
            options={'verbose_name': 'ProjectPlantUnit', 'verbose_name_plural': 'ProjectPlantUnits'},
        ),
        migrations.RenameField(
            model_name='projectspecificinfo',
            old_name='sei',
            new_name='project_sei',
        ),
        migrations.AlterField(
            model_name='electricityplant',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='projectplant',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='projectplant',
            name='fuel_type',
            field=models.CharField(choices=[('coal', 'Coal'), ('nuclear', 'Nuclear'), ('gas', 'Gas'), ('petroleum', 'Petroleum'), ('simple-gas', 'Simple Gas'), ('wind', 'Wind'), ('other-mean', 'Other')], default='other-mean', max_length=20, verbose_name='Fuel Type'),
        ),
    ]
