# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20160817_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='biomass_elec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Biomass Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='bulk_coal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Purchased Bulk Coal Electricity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='bulk_high_eff_gas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Purchased Bulk High Efficiency Electricity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='bulk_hydro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Purchased Bulk Hydro Electricity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='bulk_nuclear',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Purchased Bulk Nuclear Electricity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='bulk_petroleum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Purchased Bulk Petroleum Electricity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='bulk_simple_gas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Purchased Bulk Simple Gas Electricity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='bulk_solar_pv_wind',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Purchased Bulk Solar and Wind Electricity'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='chp_elec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Local CHP natual gas Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='geothermal_elec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Geothermal Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='high_efficiency_gas_elec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Local High Efficiency Electricity generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='local_other_gas_elec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Local other Gas Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='other_local_elec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Other Renewable Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='turbine_elec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Local Turbine Electricity Generation'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='wind_solar_pv_elec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Wind Solar PV Electricity Generation'),
        ),
    ]
