# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20160817_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='bulk_coal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Purchased Bulk Coal Electricity'),
        ),
    ]
