# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20160818_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspecificinfo',
            name='projecr_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Project Score'),
        ),
        migrations.AlterField(
            model_name='projectplant',
            name='sei_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SEI Value'),
        ),
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='tnd_losses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T&D Losses'),
        ),
    ]
