# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20160818_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplant',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('coal', 'Coal'), ('nuclear', 'Nuclear'), ('gas', 'Gas'), ('petroleum', 'Petroleum'), ('simple-gas', 'Simple Gas'), ('wind', 'Wind'), ('other-mean', 'Other')], default='other-mean', max_length=20, null=True, verbose_name='Fuel Type'),
        ),
    ]
