# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20160818_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplant',
            name='fuel_type',
            field=models.CharField(choices=[('coal', 'Coal'), ('nuclear', 'Nuclear'), ('gas', 'Gas'), ('petroleum', 'Petroleum'), ('simple-gas', 'Simple Gas'), ('wind', 'Wind'), ('other-mean', 'Other')], default='other-mean', max_length=20, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='projectplant',
            name='type',
            field=models.CharField(blank=True, choices=[('TRL', 'Thermal'), ('HDR', 'Hydro'), ('PV', 'PV')], max_length=10, null=True, verbose_name='Plant Type'),
        ),
    ]
