# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20160818_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspecificinfo',
            name='project_sei',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Project SEI value'),
        ),
    ]
