# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
